### ISSUE TITLE
Automated browser-laptop builds sometimes crashing in TP

### ISSUE THREAD

**Issue by bbondy** [SergeyZhukovsky/tracking-protection#13]
<img width="880" alt="screenshot 2016-11-12 00 28 09" src="https://cloud.githubusercontent.com/assets/831718/20235907/0ee06290-a86f-11e6-820c-25b296f5aa0a.png">

**Comment by SergeyZhukovsky** [comment]
@bbondy what are those tests? Could I run them? It looks like corrupted buffer for deserialization.

**Comment by bbondy** [comment]
they are just tests that start the browser, do some task and then close the browser. They download TP on startup like it is normal to do.  So you suspect the file somehow gets corrupted?

**Comment by bbondy** [comment]
but it also happened I seen on dev channel recently, and so it seems like probably not corrupted data file.

**Comment by bbondy** [comment]
Why does it go inside HashSet deserialize and then back into ST_FIRST_PARTY_HOST deserialize? I am a bit confused about the stack because of that.

**Comment by SergeyZhukovsky** [comment]
It is all ok to me with a callstack. HashSet is a set of ST_FIRST_PARTY_HOST object. So it calls deserialize for each object inside it.

**Comment by SergeyZhukovsky** [comment]
I'm going to try deserialize with an existing .dat file in a loop.

**Comment by SergeyZhukovsky** [comment]
Fixed memory corruption using XCode memory sanitizer. Please try the new version with your tests.
