### ISSUE TITLE
platform.linkedin.com link wrongly blocked on businessinsider.com 

### ISSUE THREAD

**Issue by bbondy** [SergeyZhukovsky/tracking-protection#2]
The slideshow here:
http://www.businessinsider.com/yahoo-roaring-20s-holiday-party-pictures-2015-12?op=0#/%23yahoos-20th-anniversary-holiday-party-was-roaring-20s-themed-1

has a problem with tracking protection. 
It works with Chrome with Disconnect installed.

But does not load with Brave because brave blocks it.
the host of lookup that gets blocked is:
platform.linkedin.com
And it finds it should block with that.

Then it looks for exceptions from:
businessinsider.com but does not find any.

**Comment by bbondy** [comment]
Another case we shouldn't block, go to:
https://www.khanacademy.org/
Click on login, then click on facebook.
Does not load.

**Comment by SergeyZhukovsky** [comment]
The first website works ok, the same as Chrome's Disconnect. You used a wrong list originally.
Made a temp fix for second to allow 'connect.facebook.net'. We will handle that in future when have a popup to unblock domains.
