### ISSUE TITLE
npm ERR! tracking-protection@1.0.8 install: `node-gyp rebuild`

### ISSUE THREAD

**Issue by inside** [SergeyZhukovsky/tracking-protection#4]
Hi,

When trying to install the [brave browser](https://github.com/brave/browser-laptop), I ran into the error below with tracking-protection@1.0.7 or tracking-protection@1.0.8.

Npm and node versions are the latest at this time. I'm running ubuntu. I've also attached the npm-debug.log file.

If you have any info, please let me know.

Regards,

Versions of software used:
```
% npm --version
3.5.3
% node --version
v4.2.6
% lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty
% uname -a
Linux subway 3.13.0-76-generic #120-Ubuntu SMP Mon Jan 18 15:59:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

Error message:
```
npm ERR! tracking-protection@1.0.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tracking-protection@1.0.8 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the tracking-protection package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs tracking-protection
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls tracking-protection
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/yann/src/browser-laptop/npm-debug.log
```
[npm-debug.log.zip](https://github.com/SergeyZhukovsky/tracking-protection/files/100615/npm-debug.log.zip)

**Comment by SergeyZhukovsky** [comment]
Are you sure it is the latest node? They have 5.x.x already. Please update it and try again.
Thanks for trying to build our browser.

**Comment by inside** [comment]
You are right indeed, 4.x.x is the LTS version, 5.x.x is the stable one. But I have the same installation error even with node `v5.5.0`. Please see the full npm log attached.

Thanks in advance for your reply.

[npm-debug.log.zip](https://github.com/SergeyZhukovsky/tracking-protection/files/100788/npm-debug.log.zip)

**Comment by inside** [comment]
I remove node-gyp globally by issuing this command as root: `npm rm node-gyp -g` and I could successfully install and run brave!!

**Comment by SergeyZhukovsky** [comment]
Great, as I was thinking what it could be on your side :).
Thanks for trying the browser.

**Comment by inside** [comment]
Thank you for your time!
